### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by lpandzic** [Randgalt/record-builder#103]
Hello, I see last release was 16 days ago and I'd really like to use the features that are present in master but haven't been released yet. When is a new release going to happen?

**Comment by Randgalt** [comment]
Hi - I want to complete the 2 PRs that are remaining. This one just needs a review: https://github.com/Randgalt/record-builder/pull/102 - the other I'm nearly done with. I'll try to release by Friday or Monday at the latest.

**Comment by lpandzic** [comment]
Ok, thanks!
