### ISSUE TITLE
Suggestion: protected constructor on builder

### ISSUE THREAD

**Issue by jedvardsson** [Randgalt/record-builder#121]
Hi, I appreciate all you work on this project. Thank you. 

What do you think about generating abstract builder classes (similar to AutoValue). This would allow for greater flexibility to add convenience methods and implement other interfaces? Like so,

```
@RecordBuilder
public record Example(String name) {

    public static CatalogBuilder newBuilder() {
        return new Builder();
    }
    
    public static final class Builder extends ExampleBuilder implement OtherStuff {
    }
}
```

**Comment by Randgalt** [comment]
The only thing needed for this is that the generated builder's constructor isn't `private` right?

**Comment by jedvardsson** [comment]
Yes, I suppose so. However, the newBuilder-method on the builder class will not work as expected. Therefore, to keep compatibility it might be better to make the generated builder abstract and add an abstract newBuilder-method, or leave it out entirely. Maybe new flag on the annotation `abstractBuilder=true`?

**Comment by jedvardsson** [comment]
Maybe this isn't a good idea after all. Careless subclassing might messup equals and hashcode.

**Comment by fprochazka** [comment]
I'm using it like this

```java
@MyRecordBuilder
public record Costs(
    @Nullable BigDecimal shipping,
    @Nullable BigDecimal tax
)
{

    public CostsBuilder toBuilder()
    {
        return CostsBuilder.builder(this);
    }

    public static CostsBuilder builder()
    {
        return CostsBuilder.builder();
    }

}
```

IMHO it's not that much more work to add these two methods.

**Comment by jedvardsson** [comment]
@fprochazka, we are not talking about the “factory” methods which indeed are public already, but the the private constructor which prevents subclassing. However, it might not be a good idea after allow that. 

Any way, thanks for trying to help out. 👍

**Comment by fprochazka** [comment]
Yeah, I got that, I was just wondering *why* you'd want to subclass it?

**Comment by toolforger** [comment]
Those who want to leverage the Builder as a parent class for a Java Bean.
See #128.

**Comment by jedvardsson** [comment]
To implement interfaces and add additional methods.

**Comment by jahlbornG** [comment]
any plans to add support like this?  i would love a good way to customize the builder.  i've often wanted to add convenience methods to the builder.  for example, i often use records for collections of options.  there may be a common collection of options and i'd love to be able to add a convenience method like:

**Comment by Randgalt** [comment]
At this point I'd like to limit any new customizations. This library ran into a lot of problems with some of the recently added customizations.

**Comment by Randgalt** [comment]
The latest release has an option to make the ctors public
