### ISSUE TITLE
Add a simple way to remove items from a collection. 

### ISSUE THREAD

**Issue by joakim-eriksson** [Randgalt/record-builder#125]
With the latest changes there is no easy and clean way to remove or replace items from a collection. Before one would always get a mutable collection when using the get methods, this has now changed. Maybe add remove and replace methods to the generated builders.

**Comment by Randgalt** [comment]
Can you give a quick code example of how you were using it before?

**Comment by joakim-eriksson** [comment]
I have changed my mind on this, more advanced features of the collection classes is better handled outside of the builder.
