### ISSUE TITLE
generate "add" method for collections

### ISSUE THREAD

**Issue by maxandersen** [Randgalt/record-builder#142]
given this:

`record Rule(String name, Filter filter, List<Action>) {}`

I would love I could do:

`RuleBuilder.name("arule").filter(f().from("max@acme.org")).action(markAsSeen()).action(fileTo("folder")).build()`

Basically, in addition to generating `action(List<Action>)` add a `action(Action)` that builds up the list.

**Comment by Randgalt** [comment]
Add this:

```
@RecordBuilder.Options(addSingleItemCollectionBuilders = true, useImmutableCollections = true)
```
