### ISSUE TITLE
@RecordInterface.Include() on package declaration of package-info.java

### ISSUE THREAD

**Issue by stbischof** [Randgalt/record-builder#143]
I would like to have the `@RecordInterface.Include()` on `package` declaration of `package-info.java`.
```
@RecordInterface.Include(
package org.eclipse.daanse.odf.model.record;


```

**Comment by Randgalt** [comment]
This is already supported. There is an example here: https://github.com/Randgalt/record-builder/blob/master/record-builder-test/src/main/java/io/soabase/recordbuilder/test/package-info.java
