### ISSUE TITLE
@RecordBuilder.Include(packages="foo") should handle Options

### ISSUE THREAD

**Issue by stbischof** [Randgalt/record-builder#148]
would be great if `RecordBuilder.Include` provides a way to set Options.

**Comment by Randgalt** [comment]
It does. Just add `@RecordBuilder.Options(...)`.

**Comment by stbischof** [comment]
But not when you annotate a package

**Comment by Randgalt** [comment]
OK - so we just need to update the annotation? A PR for that would be appreciated.
