### ISSUE TITLE
ElementUtils relies on toString() to get package name

### ISSUE THREAD

**Issue by mbarbero** [Randgalt/record-builder#15]
Depending on the implementation of `javax.lang.model.element.Element`, the `toString` method may return different values.

It has been discovered while trying to execute the annotation processor within the Java support for vscode (https://github.com/eclipse/eclipse.jdt.ls/issues/1629) where the `Element` class is implemented by the Eclipse JDT compiler.

I'll provide a PR with a fix shortly.

**Comment by Randgalt** [comment]
Fixed by #16
