### ISSUE TITLE
Questions regarding `record-builder-validator`

### ISSUE THREAD

**Issue by ChristianCiach** [Randgalt/record-builder#158]
Hi, thanks for building this neat tool!

I've seen the artifact `record-builder-validator` on maven central and have a few questions:

* Is this artifact ready to be used? I cannot find any documentation for this. The README doesn't mention it at all.
* If so, *how* should it be used?
* The class [RecordBuilderValidator](https://github.com/Randgalt/record-builder/blob/master/record-builder-validator/src/main/java/io/soabase/recordbuilder/validator/RecordBuilderValidator.java) seems to be hardcoded to load classes from the package `javax.validation`, but we've completely migrated to `jakarta.validation` since Spring Boot 3.0. How to proceed?

We currently do not depend on this artifact, but I am curious about it.

**Comment by Randgalt** [comment]
It's optional in case you don't want to use another validator. It's only used in tests for RecordBuilder right now. I forget, but at one point it was used in the main project but got broken out at some point.
