### ISSUE TITLE
Provide documentation how to manually provide annotation processors in maven/gradle

### ISSUE THREAD

**Issue by krzyk** [Randgalt/record-builder#188]
During builds javac prints out following info (from maven):
```
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
```

It would be good to provide documentation in README how to provide the annotation processor for record builder so the above warning will disappear.

And more importantly, it is required for JDK 23, because annotation processors are not searched on the class path anymore.
(https://inside.java/2024/06/18/quality-heads-up/)

**Comment by mk868** [comment]
I think this is solved by https://github.com/Randgalt/record-builder/pull/194

**Comment by Randgalt** [comment]
It's in the README now (https://github.com/Randgalt/record-builder?tab=readme-ov-file#maven).
