### ISSUE TITLE
JSR303 @Valid is not getting filtered out

### ISSUE THREAD

**Issue by elyse-yao** [Randgalt/record-builder#189]
I have the record:
`public record Foo(String id, @Valid @NotNull Bar properties)
        implements FooBuilder.With {}`

And I'm getting this error:
`A method return value must not be marked for cascaded validation more than once in a class hierarchy, but the following two methods are marked as such: With#properties(), Foo#properties()`

I saw in the [record-builder processor source](https://github.com/Randgalt/record-builder/blob/c168f33dda2c5a00e7a0b80d510477af8c1570b7/record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java#L866) that it's meant to be filtered out, but that only applies to the `javax` version of the annotation, not the `jakarta.validation.Valid` used in spring. I know I can just disable all annotation inheritance, but Is there a way to configure record-builder to filter out specific annotations instead?

**Comment by Randgalt** [comment]
Right - the `jakarta` rename mess. We should update for that and filter both. I'd appreciate a PR with this change.

**Comment by elyse-yao** [comment]
(^ @Randgalt small bump for the PR, sorry for the delay!)
