### ISSUE TITLE
support naked main / empty packages

### ISSUE THREAD

**Issue by maxandersen** [Randgalt/record-builder#190]
in Java 23 preview you can have naked main that cannot be in a package; when I try use record-builder it seem to use classname as package:

demo.java:
```java
import io.soabase.recordbuilder.core.RecordBuilder;

@RecordBuilder
record Person(String name, int age) {};

void main() {
    System.out.println("Hello, World");
}
```

result in a generated class named: `demoPersonBuilder.java` and inside it  generates:

```
 @Generated("io.soabase.recordbuilder.core.RecordBuilder")
    public static demo.Person Person(String name, int age) {
        return new demo.Person(name, age);
    }
```

which does not work/compile.

**Comment by maxandersen** [comment]
btw. this works:

```java
package mypackage;

import io.soabase.recordbuilder.core.RecordBuilder;

@RecordBuilder
record Person(String name, int age) {};

class demo {
void main() {

    var fb = PersonBuilder.builder().name("John").age(20).build();
    System.out.println("Hello, World: " + fb);
}

}
```

but would love to remove all the unnecessary parts :)

**Comment by maxandersen** [comment]
might actually be a limitation of naked mains.

Funny enough I can put the records in a separate file and it works.

**Comment by Randgalt** [comment]
I don't know `jbang` at all. I did some quick tests and I'm probably not using it correctly. However, I created this record in the RecordBuilder source and it generates correctly. I believe whatever you're seeing is  a `jbang` bug.

```
import io.soabase.recordbuilder.core.RecordBuilder;

import java.time.Instant;

@RecordBuilder
public record NoPackage(Instant dateTime) implements NoPackageBuilder.With {
}
```

**Comment by Randgalt** [comment]
Update: I'm reproducing something now. Stay tuned...
