### ISSUE TITLE
Sealed wither interface?

### ISSUE THREAD

**Issue by bowbahdoe** [Randgalt/record-builder#27]
Its still down the line (Java 17, most likely), but it would be nice to have the `RecordName.With` generated interface be sealed so that only the record can implement it

**Comment by Randgalt** [comment]
Yeah - could do. I'll look into it.

**Comment by Randgalt** [comment]
It makes more sense to do this for Java 17 when the early builds come out. We wouldn't want to force people to add `--enable-preview` for Java 16.

**Comment by z1065485649** [comment]
I can't find the class nameandagebuilder under the next idea because I didn't install a plug-in. How do I deal with this

**Comment by Randgalt** [comment]
> I can't find the class nameandagebuilder under the next idea because I didn't install a plug-in. How do I deal with this

NameAndAgeBuider? That's a generated class. This is an annotation processor that generates Java files. No plugin needed.

**Comment by z1065485649** [comment]
Hello, but I compiled and reported errors with idea. He couldn't find the generated class. How to deal with this

**Comment by Randgalt** [comment]
@z1065485649 NameAndAgeBuilder is just an example in the documentation. There is no NameAndAge class in this project. The documentation is showing what the results would be if you had a NameAndAge class.

**Comment by Randgalt** [comment]
> Hello, but I compiled and reported errors with idea. He couldn't find the generated class. How to deal with this

If you have errors or problems please create an Github Issue and I'll see if I can help. Post your project somewhere or some example files.

**Comment by Randgalt** [comment]
After investigating this I don't think this is worthwhile. The annotation processor would have to add the permits clause and it would be complicated and not add much value.

**Comment by danp11** [comment]
Hi again Jordan

I hope you don't mind that I ask you to reopen this "issue".

Building systems/good software is IMHO alot about designing the domain model. (I'm a decent Java programmer, but old enough to have appreciated a good old and clever database design :-)) 

And as records is more about composition than inheritance this ticket would be gold to keep open IMHO. When Java 17 is out we can have another discussion about the reporter's initial proposal. My two cents is that that makes sense. 

Thanks for your good work and the exciting last days commit :-)
Nice weekend,

/Dan

**Comment by Randgalt** [comment]
I'll re-open for a future enhancement. It's too hard to do this right now. Javapoet doesn't support it all. I played around with hacking it into the code but it's far too ugly. When Javapoet supports Java 16 features maybe we can add this.

**Comment by Twisol** [comment]
Is there a way to sidestep this entirely, perhaps, by adding methods matching the record's accessors to the generated interface? This would ostensibly avoid the need for `_downcast` entirely, and make it unproblematic (if unconventional) to implement the interface on a different class.

Tweaking the example generated code in the README:
```java
public interface With {
    String name();
    int age();

    default NameAndAgeBuilder with() {
        return NameAndAgeBuilder.builder(new NameAndAge(name(), age()));
    }

    default NameAndAge withName(String name) {
        return new NameAndAge(name, age());
    }

    default NameAndAge withAge(int age) {
        return new NameAndAge(name(), age);
    }
}
```

**Comment by bowbahdoe** [comment]
@Twisol Thats less cool, I veto

**Comment by Randgalt** [comment]
Hmm - I didn't think of that! That's interesting. I'll play around with that when I get a chance.
