### ISSUE TITLE
Validations for the withers

### ISSUE THREAD

**Issue by danp11** [Randgalt/record-builder#47]
Hi Jordan

I'm playing around with new validation opportunities that you just have implemented. Very nice :-) 

Howevere, It seems to be a possible to sneak thru the validation when using the withers methods.

For example when letting 
RequiredRecord implement RequiredRecordBuilder.With
and 
RequiredRecord2 implement RequiredRecord2Builder.With 

I expect these two unit test to pass:

``` @Test
    void testNotNullsWithNewProperty() {
        var valid = RequiredRecordBuilder.builder().hey("hey").i(1).build();
        Assertions.assertThrows(NullPointerException.class, () -> valid.withHey(null));
    }

    @Test
    void testValidationWithNewProperty() {
        var valid = RequiredRecord2Builder.builder().hey("hey").i(1).build();
        Assertions.assertThrows(ValidationException.class, () -> valid.withHey(null));
    }
```
For the @RecordBuilder.Options(interpretNotNulls = true) 
I guess it just as easy to add Objects.reuireNonNull in appropriate with-methods 

but how to handle @RecordBuilder.Options(useValidationApi = true) ?

We dont want to perform a full validation of the entiere object via the builders static "new" method
but instead only validate the actual property. 

Please let me know your thoughts around this and I'll be happy to start with an initial PR.

Regards
Dan

**Comment by Randgalt** [comment]
Yes, I agree. For validation, you can validate individual fields (referenced as "properties" in the spec) via: https://stackoverflow.com/a/21961677/2048051. A PR would be appreciated.

**Comment by Randgalt** [comment]
I'm watching the Euros too. I can do the PR if you don't have time. Let me know.

**Comment by danp11** [comment]
Ah nice :-) I thought you had the south-american championship now also? Tonight the Swedes are playing :-) against Ukraine. 

I looked into to make code changes for the 'interpretNotNulls = true' and the Withers by adding the 
addNullCheckCodeBlock() from the add1WithMethod() but I couldn't get it to work properly. (Didn't try more than 45 minutes though :-)

If it is a 15 minutes fic for you, then please implement it and I can make a review.

Go Sweden tonight! :-) Which is your favourite team?

/Dan

**Comment by Randgalt** [comment]
I was living in Panamá but I live in Portugal now. But, they're out so I'll support England (I'm an EPL fan: ManU).

**Comment by danp11** [comment]
Ok, your github profile says Panama that why I asked about the S-A championship. Gamestart for England in 2 hours your time then:-) Later
