### ISSUE TITLE
Question abour visibility of the builder

### ISSUE THREAD

**Issue by danp11** [Randgalt/record-builder#52]
Hi Jordan

Just a quick question: Is there any reason why the builder always is public?

Im thinking if the record one has specified is package-private, would'nt be nice
if the builder was package-private as well? 

Thanks and have a nice weekend,

/Dan

**Comment by Randgalt** [comment]
I think this is just an oversight. I can't think of a reason not to match the visibility of the record itself assuming the building is in the same package.

**Comment by danp11** [comment]
Ok, thanks for your answer.  This ticket can be closed. /Dan

**Comment by Randgalt** [comment]
Actually, I think it makes sense to match the record visibility in most cases. Let's leave this open.
