### ISSUE TITLE
Suppress warnings for unchecked exception on _downcast

### ISSUE THREAD

**Issue by grahamrvvup** [Randgalt/record-builder#53]
We've quite a strict policy on warnings in our codebase so _downcast() methods are raised as issues when the code is generated. I'd created a quick update locally to add an annotation so consciously suppress the warning in that case, would you be open to accepting a PR for it?

**Comment by Randgalt** [comment]
This PR should fix the issue. I'd appreciate a review: https://github.com/Randgalt/record-builder/pull/49

**Comment by Randgalt** [comment]
Resolved by #49
