### ISSUE TITLE
Options to create unmodifiableLXYZ

### ISSUE THREAD

**Issue by danp11** [Randgalt/record-builder#56]
Hi again:-) 

Just thinking if it could be a good idea to have an new RecordBuilder.Options
like "useUnmodifiableCollections" or similar? 

And then for List/Map/Set use Collections.unmodifiableXYZ in the builder..?

What is your thoughts around this suggestion?

Have a nice weekend :-) 

/Dan

**Comment by danp11** [comment]
The option if one want's immuatble collections in the record is to specify this directly in the record like:

```public record Book (String title, int numPages, List<String> chapters) {

    public Book {
        **chapters = List.copyOf(chapters);**
    }
}```

But IMO it would be nice to let the builder take care of this.

**Comment by danp11** [comment]
Hi, I'll try to fix this one. 

PS I don't think the issue "Add emptyDefaultForCollections options #58" is a duplicate really of this enhancement.

From my understanding #58 seems to be more like the option emptyDefaultForOptional but for Collections DS

My intention in this ticket is that we do a copyOf() in the build method of the builder.

/Dan

**Comment by Randgalt** [comment]
@danp11 have you started? I think I'll handle this issue and yours in one PR.

**Comment by danp11** [comment]
Hi @Randgalt 

No, I haven't started so feel free to implement this suggestion if you want.

Thanks, 

/Dan
