### ISSUE TITLE
Add emptyDefaultForCollections options

### ISSUE THREAD

**Issue by krzyk** [Randgalt/record-builder#58]
I think many people would like to have `emptyDefaultForCollections`, where instead of nulls builder would set following instances in the record built:

* List -> List.of()
* Set -> Set.of()
* Map -> Map.of()
* Collection -> Set.of() or List.of()

**Comment by Randgalt** [comment]
Duplicate of #56

**Comment by krzyk** [comment]
@Randgalt It doesn't look like a duplicate of #56.

My proposition is to handle null gracefully by using empty List/Set/Map, while #56 is all about umodifiable collections.

**Comment by Randgalt** [comment]
OK - I guess I misunderstood. You're staying if someone passes in a null to the builder then, e.g., `List.of()` is used instead of null? I'm not sure how I feel about that. I think that would be unexpected.

**Comment by krzyk** [comment]
@Randgalt thank you
