### ISSUE TITLE
Maybe use Map::entry instead of AbstractMap.SimpleEntry?

### ISSUE THREAD

**Issue by Thihup** [Randgalt/record-builder#68]
There is a chance that using the Map::entry, it will be a primitive class and maybe will have better performace. Is there a reason to choose the AbstractMap.SimpleEntry over Map.entry or  AbstractMap.SimpleImmutableEntry?

(By the way, this project is superb)

**Comment by Randgalt** [comment]
Cargo cult coding on my part. I'll see if it can be improved.

> (By the way, this project is superb)

Wow - thank you - I really appreciate that.
