### ISSUE TITLE
Support records with 0 fields

### ISSUE THREAD

**Issue by TedCassirer** [Randgalt/record-builder#9]
This is an edge case I came across while playing around.
If you have a record with no fields the generated <class name>Builder source will have a duplicate 0 argument constructor.

Example:
```
@RecordBuilder
public record MyRecord() implements MyRecordBuilder.With{}
```
Generates:
```
@Generated("io.soabase.recordbuilder.core.RecordBuilder")
public class MyRecordBuilder {
    @Generated("io.soabase.recordbuilder.core.RecordBuilder")
    private MyRecordBuilder() {
    }

    @Generated("io.soabase.recordbuilder.core.RecordBuilder")
    private MyRecordBuilder() {
    }

   ...Rest of the class
```

This results in a compilation error

**Comment by Randgalt** [comment]
Thanks. I thought empty records were illegal. But I’ll check for it anyway

**Comment by Randgalt** [comment]
Fixed by https://github.com/Randgalt/record-builder/pull/10
